vich_uploader:
    db_driver: orm

    mappings:
        vehicule_image:
            uri_prefix: /images/vehicule_image
            upload_destination: '%kernel.project_dir%/public/images/vehicule_image'
