vich_uploader:
    db_driver: orm
    mappings:
        vehicule_image:
            uri_prefix:         '%app.path.vehicule_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.vehicule_image%'
                
            
     

    